---
- name: Node.js | Package prerequisites for node.js
  apt: pkg=software-properties-common state=present
  become: true
  tags: nodejs

- name: Curl | Install Curl
  apt: pkg=curl update-cache=yes
  become: true
  tags: nodejs

- name: Node.js | Add the Node.js PPA
  shell:
    curl -sL https://deb.nodesource.com/setup_8.x |
    sudo -E bash -
  became: true
  tags: nodejs

- name: Node.js | Install Node.js and npm
  apt: pkg=nodejs update-cache=yes
  become: true
  tags: nodejs

- name: Build-Essential | Add Build Essential Package
  apt: pkg=build-essential update-cache=yes
  become: true
  tags: nodejs