- name: Nginx | Install nginx
  become: true
  apt: pkg=nginx
  tags: nginx

- name: Nginx | Setup reverse proxy
  become: true
  template: src=default dest=/etc/nginx/sites-available/
  tags: nginx

- name: Nginx | Start nginx
  become: true
  service: name=nginx state=restarted
  tags: nginx