- name: MongoDB | Install mongodb
  apt: pkg=mongodb update-cache=yes
  become: true
  tags: mongodb

- name: MongoDB | Run mongo daemon
  become: true
  service: name=mongodb state=started
  tags: mongodb